name: 'Automatic_check CHENWUWANJIAN'

on:
  push:
  schedule:
     - cron: '2,58 0,2,4,8,10,13 * * *'  # At minute 2 and 58 past hour 8, 10, 12, 16, 18, and 21(UTC conversion, UTC+8=Chinese standard time)


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Levick
      run: |
        python ./upload.py -n 1 -u ${{ secrets.NAME_NCOV }} -p ${{ secrets.PSW_NCOV }} -f ./data/upload.txt 
#----find username and password in github secrets, please add yours to github secrets if newly forked----
